drop table if exists operate_log_t;
create table operate_log_t(
    id                 bigint generated by default as identity,
    operate_name       varchar(64),
    operate_desc       varchar(20000),
    module             int(3),
    source             int(3),
    status             int(3),
    operate_result     varchar(1024),
    primary key(id)
);

drop table if exists user;
create table user_t(
    id           bigint generated by default as identity,
    user_name    varchar(64),
    user_sex     varchar(6),
    user_age     int(3),
    primary key(id)
);